source "https://rubygems.org"

gem 'activesupport'
gem 'sinatra',           '~> 1.4.3'
gem 'sinatra-websocket', '~> 0.3.0'
gem 'less',              '~> 2.3.2'
gem 'open4',             '~> 1.3.0'
gem 'json',              '~> 1.8.0'
gem 'slim',              '>= 1.1.0'
gem 'web-socket-ruby',   '~> 0.1.0'
gem 'sidekiq',           '~> 3.2.0'
gem 'sidetiq',           '~> 0.6.1'
gem 'git',               '~> 1.2.5'
gem 'redis',             '~> 3.0.6'
gem 'jekyll',            '~> 1.1.2'
gem 'therubyracer'
gem 'sinatra-assetpack', :require => 'sinatra/assetpack'
